export const trips = [
	{
		id:0,
		title: 'Best Music in town',
		tripCaption: 'You will love this!',
		themeName: 'Music',
		destinationID: 1,
		destinationName: 'mcleodganj',
		link: '/mcleodganj/music/0',
		description: 'You will love this!',
		short_description:'Hello',
		tripDate: new Date(2019,4,10),
		upcoming: true,
		active:true,
		featured_image: "https://support.apple.com/content/dam/edam/applecare/images/en_US/music/featured-section-support-for-itunes_2x.png",
		payment_code: "https://www.instamojo.com/@singlakaran1994/l2024c47265004a188bf110f01146428a/",

	},

	{
		id:1,
		title: 'Best Food in town',
		tripCaption: 'Lets cook this together',
		themeName: 'Food',
		destinationID: 1,
		destinationName: 'mcleodganj',
		link: '/mcleodganj/food/1',
		description: 'Lets cook this together',
		short_description:'Hello',
		tripDate: new Date(2019,3,15),
		upcoming:true,
		active:true,
		featured_image: "https://image.freepik.com/free-photo/home-beautiful-kitchen-food-cooking_1303-820.jpg",
		payment_code: 'https://www.instamojo.com/singlakaran1994/test-event-e769d/',				          	
		
	},

	{
		id:2,
		title: 'The history of Rajas',
		tripCaption: 'Dive in the history and get insipred by the stories of courage!',
		themeName: 'Music',
		destinationID: 0,
		destinationName: 'udaipur',
		link: '/udaipur/history/0',
		description:'Dive in the history and get insipred by the stories of courage!',
		short_description:'Hello',
		tripDate: new Date(2019,2,11),
		upcoming:true,
		active:true,
		featured_image: "https://support.apple.com/content/dam/edam/applecare/images/en_US/music/featured-section-support-for-itunes_2x.png",
		payment_link: 'https://imjo.in/NN35MP',
		payment_code: "https://www.instamojo.com/@singlakaran1994/l2024c47265004a188bf110f01146428a/",				          	
	},
	{
		id:3,
		title: 'Best Music in town',
		tripCaption: 'You will love this!',
		themeName: 'Music',
		destinationID: 1,
		destinationName: 'mcleodganj',
		link: '/mcleodganj/music/0',
		description: 'You will love this!',
		short_description:'Hello',
		tripDate: new Date(2019,3,11),
		upcoming: true,
		active:true,
		featured_image: "https://support.apple.com/content/dam/edam/applecare/images/en_US/music/featured-section-support-for-itunes_2x.png",
		payment_code: "https://www.instamojo.com/@singlakaran1994/l2024c47265004a188bf110f01146428a/",				          	

	},
	{
		id:4,
		title: 'Best Music in town',
		tripCaption: 'You will love this!',
		themeName: 'Music',
		destinationID: 1,
		destinationName: 'mcleodganj',
		link: '/mcleodganj/music/0',
		description: 'You will love this!',
		short_description:'Hello',
		tripDate: new Date(2019,3,12),
		upcoming: true,
		active:true,
		featured_image: "https://support.apple.com/content/dam/edam/applecare/images/en_US/music/featured-section-support-for-itunes_2x.png",
		payment_code: "https://www.instamojo.com/@singlakaran1994/l2024c47265004a188bf110f01146428a/",				          	

	},
	{
		id:5,
		title: 'Best Music in town',
		tripCaption: 'You will love this!',
		themeName: 'Music',
		destinationID: 1,
		destinationName: 'mcleodganj',
		link: '/mcleodganj/music/0',
		description: '<b>You will love this!</b>',
		short_description:'Hello',
		tripDate: new Date(2019,3,13),
		upcoming: true,
		active:true,
		featured_image: "https://support.apple.com/content/dam/edam/applecare/images/en_US/music/featured-section-support-for-itunes_2x.png",
		payment_code: "https://www.instamojo.com/@singlakaran1994/l2024c47265004a188bf110f01146428a/",				          	

	},
	{
		id:6,
		title: 'Best Music in town',
		tripCaption: 'You will love this!',
		themeName: 'Music',
		destinationID: 1,
		destinationName: 'mcleodganj',
		link: '/mcleodganj/music/0',
		description: 'You will love this!',
		short_description:'Hello',
		tripDate: new Date(2019,3,10),
		upcoming: true,
		active:true,
		featured_image: "https://support.apple.com/content/dam/edam/applecare/images/en_US/music/featured-section-support-for-itunes_2x.png",
		payment_code: "https://www.instamojo.com/@singlakaran1994/l2024c47265004a188bf110f01146428a/",				          	

	},

	
]